### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by alexfolson** [whistle-plugins/whistle.sni-callback#2]
i followed the tutorial and entered:
`w2 i whistle.sni-callback`
but the npm prompted the error.

npm version: v8.5.1
node version: v17.6.0

and the screenshot below:
![image](https://user-images.githubusercontent.com/58067013/167108421-0ca38ee6-a761-40cf-809d-62a4dfb8be41.png)

**Comment by avwo** [comment]
这个是什么命令行，用 windows 自带的 cmd 看看？

**Comment by avwo** [comment]
在 Windows 系统下用该 Node 版本直接安装 Whistle（`npm i -g whistle` ）也会报上述错误，换 LTS 版本试试：https://github.com/npm/cli/issues/4234
